<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <joint name="laser_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="laser_frame"/>
    <origin xyz="${lidar_offset_X} 0 ${(chassis_height/2) + (lidar_stand_height) + (lidar_height/2)}" rpy="0 0 0"/>
  </joint>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_height}" radius="${lidar_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="laser_frame">
    <material>Gazebo/Red</material>
    <!--sensor name="laser" type="ray" JHP 2024.10.03-->
    <sensor name="laser_frame" type="gpu_lidar">
      <pose> 0.0 0.0 0.0 0.0 0.0 0.0 </pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>gz_scan</topic>
      <gz_frame_id>laser_frame</gz_frame_id>
      <frame_id>laser_frame</frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-${pi}</min_angle>
            <max_angle>${pi}</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>0.0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>


</robot>