<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="inertial_macros.xacro"/>
<xacro:include filename="robot_property.xacro"/>

    <!-- BASE LINK -->
    <link name="base_link">
    <!-- Is located center wheel axles  in mid Y and Z axes of the chassis -->
    <!-- It needs to sit above the world origin by the wheel radius -->
        <origin xyz="0.0 0.0 ${wheel_radius}"/>
    </link>

    <!-- BASE JOINT -->
    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 -${wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- BASE FOOTPRINT -->
    <!-- Represents the 'shadow'of the robot on the floor/ground -->
    <!-- It is the 2d outside dimension of the robot and minimal thickness -->
    <link name="base_footprint">
        <visual name="footprint_visual">
            <origin xyz="-${chassis_offset + caster_radius} 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length + (caster_radius * 2)} ${wheel_separation + wheel_thickness} 0.001"/>
            </geometry>
            <material name="gray"/>
        </visual>
    </link>

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>
    <link name="chassis_link">
        <visual name="chassis_gz_visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <!-- box size="${chassis_length} ${chassis_width} ${chassis_height}"/ -->
                <!-- mesh filename="package://stingray/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/-->
                <!-- mesh filename="/home/ubuntu/stingray_ws/src/stingray/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/-->
                <mesh filename="file://$(find stingray)/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <visual name="chassis_rviz_visual">
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <!-- box size="${chassis_length} ${chassis_width} ${chassis_height}"/ -->
                <mesh filename="file://$(find stingray)/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/>
                <!-- mesh filename="/home/ubuntu/stingray_ws/src/stingray/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/-->
                <!-- mesh filename="file://home/ubuntu/stingray_ws/src/stingray/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/-->
            </geometry>
            <material name="gray"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <!-- mesh filename="package://stingray/description/meshes/Stingray.stl" scale="0.001 0.001 0.001"/ -->
		        <!-- collision doesn't need to be a mesh, a box is sufficient -->
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <!-- WHEEL LINKS -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 0.13 0.0" rpy="-${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_link">
        <visual name="left_wheel_visual">
            <geometry>
                <cylinder radius="0.062" length="0.02"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <visual name="left_wheel_marker_visual">
            <origin xyz="0 ${wheel_radius*0.7} 0" rpy="0 0 0" />
            <geometry>
                <box size="${wheel_radius*0.2} ${wheel_radius*0.3} ${wheel_thickness*1.1}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.062" length="0.02"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.141" length="0.02" radius="0.062">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>


    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 -0.13 0.0" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="0.062" length="0.02"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <visual name="right_wheel_marker_visual">
            <origin xyz="0 ${-wheel_radius*0.7} 0" rpy="0 0 0" />
            <geometry>
                <box size="${wheel_radius*0.2} ${wheel_radius*0.3} ${wheel_thickness*1.1}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.062" length="0.02"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.141" length="0.02" radius="0.062">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
        <origin xyz="${caster_x_offset} 0.0 ${caster_z_offset}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <axis xyz="0.0 0.0 0.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>
    <link name="caster_wheel_link">
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius=".028"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.028"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.152" radius="0.058">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_sphere>
    </link>

</robot>
